"""Compatibility imports for Toolkit-owned language-neutral contracts."""

from inkcre_extension_toolkit.contracts import (
    CanonicalExtensionName,
    ContractModel,
    ExtensionRecord,
    ExtensionSummary,
    ModuleFederationAssociationInput,
    ModuleFederationDistribution,
    PrepareReleaseRequest,
    PythonAssociationInput,
    PythonDistribution,
    PythonEntryPoint,
    RegistrySegment,
    ReleaseRecord,
    ReleaseState,
    StrictSemVer,
    YankRequest,
    normalize_project_name,
    python_project_version,
    validate_extension_name,
    validate_host_sdk_range,
    validate_segment,
    validate_version,
)

__all__ = [
    "CanonicalExtensionName",
    "ContractModel",
    "ExtensionRecord",
    "ExtensionSummary",
    "ModuleFederationAssociationInput",
    "ModuleFederationDistribution",
    "PrepareReleaseRequest",
    "PythonAssociationInput",
    "PythonDistribution",
    "PythonEntryPoint",
    "RegistrySegment",
    "ReleaseRecord",
    "ReleaseState",
    "StrictSemVer",
    "YankRequest",
    "normalize_project_name",
    "python_project_version",
    "validate_extension_name",
    "validate_host_sdk_range",
    "validate_segment",
    "validate_version",
]
